// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMlYY4bpEPkeZNC6uAKyYPPLjH-b6rKPs',
    appId: '1:791126844053:web:3f74a7d749ffe66646b19c',
    messagingSenderId: '791126844053',
    projectId: 'internshipchat-cae66',
    authDomain: 'internshipchat-cae66.firebaseapp.com',
    storageBucket: 'internshipchat-cae66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEm8_KCK8eFg_N87ihXBOSB4d4J15kRaA',
    appId: '1:791126844053:android:01702edb39492a3946b19c',
    messagingSenderId: '791126844053',
    projectId: 'internshipchat-cae66',
    storageBucket: 'internshipchat-cae66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdQs_vtWz8uFvdaLFFbOL3kykszI7jcK4',
    appId: '1:791126844053:ios:7794ec2bbc6b837c46b19c',
    messagingSenderId: '791126844053',
    projectId: 'internshipchat-cae66',
    storageBucket: 'internshipchat-cae66.appspot.com',
    iosBundleId: 'com.example.internshipChat',
  );
}
